### ISSUE TITLE
Availability of ocean driving fields

### ISSUE THREAD

**Issue by jesusff** [WCRP-CORDEX/cmip6-for-cordex#12]
> For coupled Med-CORDEX runs, we need to have monthly mean files for 3D T, 3D S and sea level available from the driving GCMs. Would it be possible to add this in the availability criteria. I do expect those fields to be available for all GCMs as we ony need monthly-mean data

_Originally posted by @sam-somot in https://github.com/WCRP-CORDEX/cmip6-for-cordex/pull/5#discussion_r1265301419_

**Comment by jesusff** [comment]
I cannot find actual water temperature on ESGF. There are potential (thetao) and conservative (bigthetao) temperatures. I assume that salinity and sea level are:
so - Sea Water Salinity
zos - Sea Surface Height Above Geoid

@sam-somot could you check which standard variables you usually read from the ocean model as OLBC?

**Comment by jesusff** [comment]
For the record (S. Somot via e-mail):
> We need monthly-mean 3D fields for so and either thetao or bigthetao.
Also we need monthly-mean 2D fields for zos
Thetao was used for years and recently the temperature variable of the ocean models switched to bigthetao but I imagine not for all models yet in Med-CORDEX.
However the transformation between thetao and bigthetao is not that complicated. So with some efforts, both can be used by the modelling groups to drive their ocean models in the near-atlantic area.

**Comment by sam-somot** [comment]
Chus, were you able to implement this new availability criteria we discussed last year ? This would be relevant for the Med-CORDEX domain but also to any coupled RCMs in CORDEX. We could use a disable_EUR option for the domains that do not want those fields (or a able_MED if simpler)

**Comment by jesusff** [comment]
Hi, yes, this is nearly ready. I just need to do some tests before releasing it. Given the AORCM is in the CORDEX CV, I will just list the availability equally for all domains, assuming that if a GCM can drive an AORCM, it will also be valid to drive an ARCM.
